### ISSUE TITLE
Running on commodity hardware.

### ISSUE THREAD

**Issue by laliux** [tiempor3al/ExcelReader#2]
I'm getting some problems to run your lib on a minimal server (512MB7 1vCPU). Can you confirm that the library can parse 10K, 50K and 100K rows on such commodity hardware.

**Comment by tiempor3al** [comment]
I created an Ubuntu VM in VirtualBox with 768mb of memory and 1 vCPU. The library was able to parse an Excel file with 200K+ rows consuming only 17.8 MB of memory.

I attach the test file.

Regards

[dump_xrp.xlsx.tar.gz](https://github.com/tiempor3al/ExcelReader/files/1569225/dump_xrp.xlsx.tar.gz)

[test.php.tar.gz](https://github.com/tiempor3al/ExcelReader/files/1569245/test.php.tar.gz)
